### ISSUE TITLE
bluetooth on rasbian buster lite not working OOTB?

### ISSUE THREAD

**Issue by hugokoopmans** [koenvervloesem/ruuvitag-demo#1]
Hi Koen,

Just stumped by this issue that when getting a clean image the bluetooth seems not to be running OOTB?

hciconfig -a does not give any response, am I missing soething?

tx

hugo

**Comment by koenvervloesem** [comment]
That's weird, on which Raspberry Pi model is this? I get this on a Raspberry Pi 4:

```
pi@pi-red:~ $ hciconfig
hci0:   Type: Primary  Bus: UART
        BD Address: XX:XX:XX:XX:XX:XX  ACL MTU: 1021:8  SCO MTU: 64:1
        UP RUNNING 
        RX bytes:74353909 acl:3 sco:0 events:3666920 errors:0
        TX bytes:49128380 acl:5 sco:0 commands:2837718 errors:0
```

Have you enabled the [UART](https://www.raspberrypi.org/documentation/configuration/uart.md) by any chance? That could impact the Bluetooth adapter.

**Comment by hugokoopmans** [comment]
Hi Koen my bad seems the pi I had lying around has a broken bluetooth hardware...
I plugin in another pi and no issues .... thx for your quick response hugo
