### ISSUE TITLE
Access to the port from the network(outside the pi)

### ISSUE THREAD

**Issue by hugokoopmans** [koenvervloesem/ruuvitag-demo#2]
Hi Koen, 
If I would want to make the dashboards available outside the pi, inside the network it runs in ? 
Any suggestion how to do that?

Would I need to run an Nginx proxy to route all containers?

thx hugo

**Comment by koenvervloesem** [comment]
It should already be available on the IP address of the Raspberry Pi, for instance http://IP:3000 for the Grafana dashboard.

However, this is an insecure configuration for a demo. For a production setup, you should take this configuration as a first step, don't expose the ports of the Docker containers directly and add an nginx reverse proxy or Traefik, using TLS.
