### ISSUE TITLE
Zigbee example ?

### ISSUE THREAD

**Issue by martin9115** [koenvervloesem/ruuvitag-demo#5]
Hi, have you try to run this project with Zigbee ?

**Comment by koenvervloesem** [comment]
I'm not sure what you're asking. The RuuviTag is a Bluetooth Low Energy device, it doesn't speak Zigbee. If you want to collect information from Zigbee sensors, have a look at [Zigbee2MQTT](https://www.zigbee2mqtt.io). You can still use Node-RED, Telegraf, InfluxDB and Grafana based on the MQTT messages Zigbee2MQTT creates from the communication of your Zigbee devices.

**Comment by martin9115** [comment]
Yes, i try, but i have problem to connect Xbee/Zigbee with Node-red

**Comment by koenvervloesem** [comment]
Sorry, I can't help with that. I'm closing this issue because it's not relevant to the ruuvitag-demo repository.
